package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

// Alert is a user-facing notification generated by any engine.
// RefID points to the source record (Threat, NetworkEvent, or ProcessEvent).
type Alert struct {
	ID        string    `gorm:"primaryKey;type:text"`
	Title     string    `gorm:"type:text;not null"`
	Message   string    `gorm:"type:text"`
	Severity  string    `gorm:"type:text"` // info | warning | high | critical
	Source    string    `gorm:"type:text"` // file | network | process
	RefID     string    `gorm:"type:text"` // ID of the related Threat / NetworkEvent / ProcessEvent
	Status    string    `gorm:"type:text"` // unread | acknowledged | dismissed
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (a *Alert) BeforeCreate(tx *gorm.DB) error {
	if a.ID == "" {
		a.ID = uuid.NewString()
	}
	return nil
}
